src/main/java/com/csum/model/Hearing.java
package com.csum.model;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;
import org.springframework.format.annotation.DateTimeFormat;

import com.csum.utils.CSUMDateUtils;

@Entity
@Table(name = "HEARING")
@Audited
@AuditTable(value = "HEARING_HSTRY")
@NamedQueries({
@NamedQuery(name="com.csum.model.hearing.findByViolationId", query="Select h from Hearing h where h.violation.violationId = :violationId"),
@NamedQuery(name="com.csum.model.hearing.findLatestByDate", query="SELECT h FROM Hearing h WHERE h.hearingDate = :hearingDate"),
@NamedQuery(name="com.csum.model.hearing.findAllPending", query="SELECT h FROM Hearing h WHERE (h.hearingDate= :hearingDate OR h.hearingDate='' OR h.hearingDate is NULL) AND h.status ='Pending'  order by hearingTime asc"),
@NamedQuery(name="com.csum.model.hearing.findAllPendingByType", query="SELECT h FROM Hearing h WHERE h.hearingDate= :hearingDate AND h.type=:type AND h.status ='Pending' order by hearingTime asc"),
@NamedQuery(name="com.csum.model.hearing.findAllPendingBetween", query="SELECT h FROM Hearing h WHERE (h.hearingDate BETWEEN :hearingDate1 AND :hearingDate2  OR h.hearingDate='' OR h.hearingDate is NULL) AND h.status ='Pending'  order by hearingTime asc"),
@NamedQuery(name="com.csum.model.hearing.findAllPendingByTypeBetween", query="SELECT h FROM Hearing h WHERE h.hearingDate BETWEEN :hearingDate1 AND :hearingDate2 AND h.type=:type AND h.status ='Pending' order by hearingTime asc"),
@NamedQuery(name="com.csum.model.hearing.findAllPendingWritten", query="SELECT h FROM Hearing h WHERE h.type='Written' AND h.status ='Pending' order by hearingTime asc"),
@NamedQuery(name="com.csum.model.hearing.findAllCompleted", query="SELECT h FROM Hearing h WHERE h.status !='Pending' AND h.hearingDate= :hearingDate order by hearingDate asc, hearingTime asc"),
@NamedQuery(name="com.csum.model.hearing.findAllCompletedStatuses", query="SELECT h FROM Hearing h WHERE (h.status = :status1 OR h.status = :status2) AND h.hearingDate= :hearingDate order by  hearingDate asc, hearingTime asc"),
@NamedQuery(name="com.csum.model.hearing.findAllCompletedStatus", query="SELECT h FROM Hearing h WHERE h.status = :status AND h.hearingDate= :hearingDate order by  hearingDate asc, hearingTime asc"),
@NamedQuery(name="com.csum.model.hearing.findAllCompletedBetween", query="SELECT h FROM Hearing h WHERE h.status !='Pending' AND h.hearingDate BETWEEN :hearingDate1 AND :hearingDate2 order by  hearingDate asc, hearingTime asc"),
@NamedQuery(name="com.csum.model.hearing.findAllCompletedBetweenStatuses", query="SELECT h FROM Hearing h WHERE (h.status = :status1 OR h.status = :status2) AND h.hearingDate BETWEEN :hearingDate1 AND :hearingDate2 order by  hearingDate asc, hearingTime asc"),
@NamedQuery(name="com.csum.model.hearing.findAllCompletedBetweenStatus", query="SELECT h FROM Hearing h WHERE h.status = :status AND h.hearingDate BETWEEN :hearingDate1 AND :hearingDate2 order by  hearingDate asc, hearingTime asc"),

})
public class Hearing extends AbstractDomain {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5356689528383171922L;
	
	@OneToOne
	@JoinColumn(name = "VLN_ID", nullable = false, updatable = false)
	private Violation violation;

	@Column(name = "HEARING_DATE")
	@DateTimeFormat(pattern = "MM/dd/yyyy")
	private LocalDate hearingDate;

	@Temporal(TemporalType.TIME)
	@Column(name = "HEARING_TIME")
	@DateTimeFormat(pattern = "HH:mm")
	private Date hearingTime;
	
	@Column(name = "HEARING_OFFICER")
	private String hearingOfficer;
	
	@Column(name = "DIPOSITION_DATE")
	@DateTimeFormat(pattern = "MM/dd/yyyy")
	private LocalDate dispositionDate;

	@Temporal(TemporalType.TIME)
	@Column(name = "DISPOSITION_TIME")
	@DateTimeFormat(pattern = "HH:mm")
	private Date dispositionTime;

	@Column(name = "DISPOSITION")
	private String disposition;
	
	@Column(name = "TOT_DUE", columnDefinition = "DECIMAL(7,2)")
	private BigDecimal totalDue;
	
	@Column(name = "noFineChange", columnDefinition = "TINYINT(1)")
	private boolean noFineChange;
	
	@Column(name = "TYPE")
	private String type;
	
	@Column(name = "STATUS")
	private String status;
	
	@Column(name = "SCHEDULED_BY")
	private String scheduledBy;

	@Column(name = "SCHEDULED_AT")
	@DateTimeFormat(pattern = "MM/dd/yyyy hh:mm a")
	private Date scheduledAt;
	
	@Column(name = "DATE_MAILED")
	@DateTimeFormat(pattern = "MM/dd/yyyy")
	private LocalDate dateMailed;
	
	@Column(name = "IS_RESCHEDULED")
	private boolean rescheduled;
	
	@OneToOne
	@JoinColumn(name = "DECISION")
	@NotAudited
	private HearingDecision decision;
	
	@Transient
	private HearingDetail hearingdetail;
	
	@Transient
	private String requiredDate;

	@Transient
	private String HearingBasis;
	
	@NotAudited
	@OneToMany(mappedBy = "hearing", fetch = FetchType.EAGER)
	private Set<HearingDetail> hearingdetails;
	
	@Column(name = "REDUCTION", columnDefinition = "DECIMAL(7,2)")
	private BigDecimal reduction;

	@Transient
	private String searchType;

	@Transient
	private String searchValue;
	
	@Transient
	private String hearingOfficerName;
	
	public String getHearingOfficerName() {
		return hearingOfficerName;
	}

	public void setHearingOfficerName(String hearingOfficerName) {
		this.hearingOfficerName = hearingOfficerName;
	}

	public String getSearchType() {
		return searchType;
	}

	public void setSearchType(String searchType) {
		this.searchType = searchType;
	}

	public String getSearchValue() {
		return searchValue;
	}

	public void setSearchValue(String searchValue) {
		this.searchValue = searchValue;
	}

	public BigDecimal getReduction() {
		return reduction;
	}

	public void setReduction(BigDecimal reduction) {
		this.reduction = reduction;
	}

	public String getRequiredDate() {
		return requiredDate;
	}

	public void setRequiredDate(String requiredDate) {
		this.requiredDate = requiredDate;
	}

	public String getHearingBasis() {
		return HearingBasis;
	}

	public void setHearingBasis(String hearingBasis) {
		HearingBasis = hearingBasis;
	}

	public Violation getViolation() {
		return violation;
	}

	public void setViolation(Violation violation) {
		this.violation = violation;
	}

	public LocalDate getHearingDate() {
		return hearingDate;
	}

	public void setHearingDate(LocalDate hearingDate) {
		this.hearingDate = hearingDate;
	}

	public Date getHearingTime() {
		return hearingTime;
	}

	public void setHearingTime(Date hearingTime) {
		this.hearingTime = hearingTime;
	}

	public String getHearingOfficer() {
		return hearingOfficer;
	}

	public void setHearingOfficer(String hearingOfficer) {
		this.hearingOfficer = hearingOfficer;
	}

	public LocalDate getDispositionDate() {
		return dispositionDate;
	}

	public void setDispositionDate(LocalDate dispositionDate) {
		this.dispositionDate = dispositionDate;
	}

	public Date getDispositionTime() {
		return dispositionTime;
	}

	public void setDispositionTime(Date dispositionTime) {
		this.dispositionTime = dispositionTime;
	}

	public String getDisposition() {
		return disposition;
	}

	public void setDisposition(String disposition) {
		this.disposition = disposition;
	}

	public BigDecimal getTotalDue() {
		return totalDue;
	}

	public void setTotalDue(BigDecimal totalDue) {
		this.totalDue = totalDue;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getScheduledBy() {
		return scheduledBy;
	}

	public void setScheduledBy(String scheduledBy) {
		this.scheduledBy = scheduledBy;
	}

	public Date getScheduledAt() {
		return scheduledAt;
	}

	public void setScheduledAt(Date scheduledAt) {
		this.scheduledAt = scheduledAt;
	}

	public LocalDate getDateMailed() {
		return dateMailed;
	}

	public void setDateMailed(LocalDate dateMailed) {
		this.dateMailed = dateMailed;
	}
	
	public boolean isNoFineChange() {
		return noFineChange;
	}

	public void setNoFineChange(boolean noFineChange) {
		this.noFineChange = noFineChange;
	}

	public boolean isRescheduled() {
		return rescheduled;
	}

	public void setRescheduled(boolean rescheduled) {
		this.rescheduled = rescheduled;
	}

	public HearingDecision getDecision() {
		return decision;
	}

	public void setDecision(HearingDecision decision) {
		this.decision = decision;
	}

	public HearingDetail getHearingdetail() {
		return hearingdetail;
	}

	public void setHearingdetail(HearingDetail hearingdetail) {
		this.hearingdetail = hearingdetail;
	}

	public Set<HearingDetail> getHearingdetails() {
		return hearingdetails;
	}

	public void setHearingdetails(Set<HearingDetail> hearingdetails) {
		this.hearingdetails = hearingdetails;
	}

	public String getFormattedHearingDate() {
		return CSUMDateUtils.getFormattedLocalDate(this.hearingDate);
	}
	
	public String getFormattedDispDate() {
		return CSUMDateUtils.getFormattedLocalDate(this.dispositionDate);
	}
	
	public String getFormattedDateMailed() {
		return CSUMDateUtils.getFormattedLocalDate(this.dateMailed);
	}
	

src/main/java/com/csum/model/HearingScheduler.java
package com.csum.model;

import javax.persistence.Entity;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

@Entity
@Table(name = "HEARING_SCHEDULER")
@NamedQuery(name = "com.csum.model.HearingScheduler.findAll", query = "SELECT s FROM HearingScheduler s")
public class HearingScheduler extends AbstractDomain {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2005459140848554858L;

	private String value;
	
	private String description;
	
	private String type;

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

}


src/main/java/com/csum/model/Permit.java
package com.csum.model;

import java.time.LocalDate;
import java.time.LocalTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;
import org.hibernate.envers.RelationTargetAuditMode;
import org.hibernate.search.annotations.IndexedEmbedded;
import org.springframework.format.annotation.DateTimeFormat;

import com.csum.utils.CSUMDateUtils;

@Entity
@Audited
@AuditTable(value = "PERMIT_HSTRY")
@Table(name = "PERMIT")
@NamedQueries({
		@NamedQuery(name = "com.csum.model.permit.findByPermitId", query = "Select p from Permit p where p.permitId=:permitId"),
		@NamedQuery(name = "com.csum.model.permit.findValidPermit", query = "Select p from Permit p where p.licenceNumber = :licenceNumber AND p.parkingSlot = :parkingSlot "
				+ "AND (:scannedDateTime BETWEEN  STR_TO_DATE(CONCAT(p.startDate,' ',p.startTime ),'%Y-%m-%d %H:%i:%s') AND STR_TO_DATE(CONCAT(p.endDate,' ',p.endTime ),'%Y-%m-%d %H:%i:%s' )) ") })

public class Permit extends AbstractDomain {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8918524430798382718L;

	@Column(name = "PERMIT_ID")
	private String permitId;

	@Column(name = "PATRON_TYPE")
	private String patronType;

	@Column(name = "PERMIT_TYPE")
	private String permitType;

	@Column(name = "Amount")
	private String amount;

	@Column(name = "FIRST_NAME")
	private String firstName;

	@Column(name = "MIDDLE_NAME")
	private String middleName;

	@Column(name = "LAST_NAME")
	private String lastName;

	@Column(name = "LIC_NUM")
	private String licenceNumber;

	@Column(name = "CSU_ID")
	private String csuId;

	@Column(name = "PARKING_SLOT")
	private String parkingSlot;

	@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
	@OneToOne
	@JoinTable(name = "PRMT_PYMNT", joinColumns = @JoinColumn(name = "PERMIT_ID", referencedColumnName = "id"), inverseJoinColumns = @JoinColumn(name = "PERMIT_PAYMENT_ID", referencedColumnName = "id"))
	@IndexedEmbedded
	private PermitPayments permitPayments;

	@Transient
	private String timeSlot;

	@Column(name = "START_DATE")
	@DateTimeFormat(pattern = "MM/dd/yyyy")
	private LocalDate startDate;

	@Column(name = "END_DATE")
	@DateTimeFormat(pattern = "MM/dd/yyyy")
	private LocalDate endDate;

	@Column(name = "START_TIME")
	@DateTimeFormat(pattern = "hh:mm a")
	private LocalTime startTime;

	@Column(name = "END_TIME")
	@DateTimeFormat(pattern = "hh:mm a")
	private LocalTime endTime;
	
	@Transient
	private String noOfMonths;
	
	@Column(name = "TYPE")
	private String type;
	
	@Column(name = "COMMENT")
	private String comment;

	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getNoOfMonths() {
		return noOfMonths;
	}

	public void setNoOfMonths(String noOfMonths) {
		this.noOfMonths = noOfMonths;
	}

	public String getPermitId() {
		return permitId;
	}

	public void setPermitId(String permitId) {
		this.permitId = permitId;
	}

	public String getTimeSlot() {
		return timeSlot;
	}

	public void setTimeSlot(String timeSlot) {
		this.timeSlot = timeSlot;
	}

	public String getPatronType() {
		return patronType;
	}

	public void setPatronType(String patronType) {
		this.patronType = patronType;
	}

	public String getPermitType() {
		return permitType;
	}

	public void setPermitType(String permitType) {
		this.permitType = permitType;
	}

	public String getAmount() {
		return amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getMiddleName() {
		return middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getLicenceNumber() {
		return licenceNumber;
	}

	public void setLicenceNumber(String licenceNumber) {
		this.licenceNumber = licenceNumber;
	}

	public String getCsuId() {
		return csuId;
	}

	public void setCsuId(String csuId) {
		this.csuId = csuId;
	}

	public PermitPayments getPermitPayments() {
		return permitPayments;
	}

	public void setPermitPayments(PermitPayments permitPayments) {
		this.permitPayments = permitPayments;
	}

	public String getParkingSlot() {
		return parkingSlot;
	}

	public void setParkingSlot(String parkingSlot) {
		this.parkingSlot = parkingSlot;
	}

	public LocalDate getStartDate() {
		return startDate;
	}

	public void setStartDate(LocalDate startDate) {
		this.startDate = startDate;
	}

	public LocalDate getEndDate() {
		return endDate;
	}

	public void setEndDate(LocalDate endDate) {
		this.endDate = endDate;
	}

	public LocalTime getStartTime() {
		return startTime;
	}

	public void setStartTime(LocalTime startTime) {
		this.startTime = startTime;
	}

	public LocalTime getEndTime() {
		return endTime;
	}

	public void setEndTime(LocalTime endTime) {
		this.endTime = endTime;
	}
	
	public String getFormattedStartDate(){
		return CSUMDateUtils.getFormattedLocalDate(this.startDate);
		
	}
	
	public String getFormattedEndDate(){
		return CSUMDateUtils.getFormattedLocalDate(this.endDate);
		
	}
	
	public String getFormattedStartTime(){
		return CSUMDateUtils.getFormattedLocalTime(this.startTime);		
	}
	
	public String getFormattedEndTime(){
		return CSUMDateUtils.getFormattedLocalTime(this.endTime);
	}
}

src/main/java/com/csum/view/model/ConvertedImage.java
package com.csum.view.model;

public class ConvertedImage {

	private long fId;
	private String fName;

	public ConvertedImage() {
	}

	public ConvertedImage(long fId, String fName) {
		super();
		this.fId = fId;
		this.fName = fName;
	}

	public long getfId() {
		return fId;
	}

	public void setfId(long fId) {
		this.fId = fId;
	}

	public String getfName() {
		return fName;
	}

	public void setfName(String fName) {	
		this.fName = fName;
	}

}

src/main/webapp/WEB-INF/views/pages/printpdfpages.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ page isELIgnored="false"%>
<!DOCTYPE html>
<html>
<head>
  <style type="text/css">
  @media print {
     @page{size:auto; margin-bottom:.5cm;}
  }
 </style>
 <title>Metro Transit Court &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Copy Printer </title>
</head>
<body onload="callPrintPages()" style="background:#173249;">
	<div>
		<h2 id="printMessage"></h2>
		<c:choose>
			<c:when test="${empty images}">
				<td colspan="3" align="center"><b>Unable to load PDF Pages.
						Try again</b></td>
			</c:when>
			<c:otherwise>
				<c:forEach items="${images}" var="page" varStatus="status">
					<div>
						<img src="<c:url value='/previewImage/${page.id}' />" />
					</div>
				</c:forEach>
			</c:otherwise>
		</c:choose>
	</div>

	<script>
	function callPrintPages() {
		window.print();
		window.onfocus=function(){
			window.close();
		}
	}
	</script>
</body>
</html>

src/main/webapp/WEB-INF/views/pages/visitorpermitinfo.jsp
<%@ page isELIgnored="false"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<!-- BEGIN CONTAINER -->
<div class="page-container">
	<div class="page-content">
		<br /> <br />
		<div class="page-bar">
			<ul class="page-breadcrumb">
				<li><a style="margin-left: 50px;"
					href="${pageContext.request.contextPath}/visitorPermitPurchase"><spring:message
							code="lbl.page.bar.permit" /></a> <i class="fa fa-circle"></i></li>
				<li><span><spring:message
							code="lbl.page.bar.permit.info" /></span></li>
			</ul>
			<!-- END PAGE HEADER-->
		</div>
		<div class="row" style="margin-right: 0px;margin-top: 10px;">
		<div class="col-md-offset-6 col-md-6">
			<a href="${pageContext.request.contextPath}/permitLogin"  class="btn blue-dark btn-sm"
					style="width: 70px; float: right;" >HOME</a>
		</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="portlet-body form">
					<div class="row">
						<div class="col-md-12">
							<!-- BEGIN EXAMPLE TABLE PORTLET-->
							<div class="portlet-title" style="margin: 20px;">
								<div class="portlet-title">
									<div class="caption">
										<span class="caption-subject sbold uppercase" style="color: #004b85;">Permit
											Info</span>
											<span class="help-block"></span>
									</div>
								</div>
								<div class="portlet-body">
									<div class="row" style="margin-bottom: 50px;">
										<div class="col-md-12">
											<table class="table  table-hover table-bordered table-sm">
												<thead>
													<tr>
														<th>Permit&nbsp;Number</th>
														<th>Permit&nbsp;Type</th>
														<th>Parking Slot</th>
														<th>Name</th>
														<th>Licence&nbsp;Number</th>
														<th>Start&nbsp;Date&nbsp;Time</th>
														<th>End&nbsp;Date&nbsp;Time</th>
														<th>Amount&nbsp;Paid</th>
													</tr>
												</thead>
												<tbody>
													<c:choose>
														<c:when test="${empty permitInfo}">
															<tr style="text-transform: uppercase;">
																<td style="text-transform: uppercase;" colspan="7"
																	align="center"><b>No results found</b></td>
															</tr>
														</c:when>
														<c:otherwise>
															<tr style="text-transform: uppercase;">
																<%-- <td><b><a onclick="enablePageLoadBar()"
																		style="color: #004b85"
																		href="<c:url value='/violationView/${permitInfo.violationId}' />">
																			<c:out value="${permitInfo.violationId}" />
																	</a></b></td> --%>
																<td><c:out
																		value="${permitInfo.permitId}" /></td>
																<td><c:out
																		value="${permitInfo.permitType}" /></td>
																<td><c:out
																		value="${permitInfo.parkingSlot}" /></td>		
																<td><c:out
																		value="${permitInfo.firstName}" /> <c:out
																		value="${permitInfo.middleName}" /> <c:out
																		value="${permitInfo.lastName}" /></td>
																<td><c:out
																		value="${permitInfo.licenceNumber}" /></td>
																<td><c:out	
																		value="${permitInfo.formattedStartDate}" /> <c:out
																		value="${permitInfo.formattedStartTime}" /></td>
																<td><c:out
																		value="${permitInfo.formattedEndDate}" /> <c:out
																		value="${permitInfo.formattedEndTime}" /></td>
																<td><c:out
																		value="${permitInfo.amount}" /></td>
															</tr>
														</c:otherwise>
													</c:choose>
												</tbody>
											</table>

											<!-- Payment Acknowledgement -->
											<c:if test="${not empty errorMessagePayment}">
												<div class="alert alert-info">
													<span>${errorMessagePayment}</span>
												</div>
												<c:choose>
													<c:when test="${empty payedInfo}">
														<tr style="text-transform: uppercase;">
															<td colspan="6" align="center"><b>No Receipt
																	found</b></td>
														</tr>
													</c:when>
													<c:otherwise>
														<div style="margin-left: 300px; width: 50%;">
															<div id="printContentId">
																<table style="font-weight: bold"
																	class="table table-bordered table-hover">

																	<tbody>
																		<tr style="text-transform: uppercase;">
																			<td style="background-color: #004b85; color: #fff"
																				colspan="2" align="center">Payment
																				Acknowledgement</td>
																		</tr>

																		<tr style="text-transform: uppercase;">
																			<td style="width: 50%">Transaction Number</td>
																			<td>${payedInfo.permitTransaction.transcationId}</td>
																		</tr>
																		<tr style="text-transform: uppercase;">
																			<td style="width: 50%">Permit Number</td>
																			<td>${permitInfo.permitId}</td>
																		</tr>
																		<tr style="text-transform: uppercase;">
																			<td style="width: 50%">Name</td>
																			<td>${permitInfo.firstName}&nbsp;${permitInfo.lastName}</td>
																		</tr>
																		<tr style="text-transform: uppercase;">
																			<td style="width: 50%">Payment Amount</td>
																			<td>${permitInfo.amount}</td>
																		</tr>
																		<%-- <tr style="text-transform: uppercase;">
																			<td style="width: 50%">Payment Type</td>
																			<td>${payedInfo.paymentMethod.description}</td>
																		</tr> --%>
																	</tbody>
																</table>
															</div>
														</div>
														<div style="margin-left: 590px;">
															<button class="btn blue-dark btn-sm icon-printer"
																onclick="printAcknowledgement('printContentId')">
																<b>PRINT</b>
															</button>
														</div>
													</c:otherwise>
												</c:choose>
											</c:if>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">

function printAcknowledgement(printContentId) {
     var preContent = "<div style='background-color:#fff'>";
     var postContent = "</div>";
     var bodyContent = document.all.item(printContentId).innerHTML;
     var currBodyCon = document.body.innerHTML;
     document.body.innerHTML = preContent+bodyContent+postContent;
     window.print();
     document.body.innerHTML = currBodyCon;
}

</script>